using System.Text.RegularExpressions;

namespace Nuons.Core.Generators;

public static class Sources
{
	private const string GeneratedExtension = ".g.cs";

	public static string GeneratedNameHint(string name) => $"{name}{GeneratedExtension}";

	public const string Tab1 = "\t";
	public const string Tab2 = "\t\t";
	public const string Tab3 = "\t\t\t";
	public const string NewLine = "\n";

	public const string GeneratedFileHeader = $@"// <auto-generated/>
// This source was generated by Nuons.
// Changes to this file may be lost when code is regenerated.
#nullable enable
#pragma warning disable
";

	public static string TrimForClassName(string assemblyName)
	{
		var trimmed = Regex.Replace(assemblyName, @"[^a-zA-Z0-9]", string.Empty);
		return $"{trimmed}_{StableHashHex(assemblyName)}";
	}

	// FNV-1a 32-bit. Stable across processes/runtimes (unlike string.GetHashCode on .NET Core).
	// Necessary to cover for case when both My.Lib and MyLib are used, unlikely but possible
	private static string StableHashHex(string value)
	{
		const uint offsetBasis = 2166136261;
		const uint prime = 16777619;
		var hash = offsetBasis;
		for (var index = 0; index < value.Length; index++)
		{
			hash ^= value[index];
			hash *= prime;
		}
		return hash.ToString("x8");
	}
}
