using System.Diagnostics;
using Nuons.Core.Abstractions;

namespace Nuons.CodeInjection.Abstractions;

/// <summary>
/// Marks a field to be injected as an <c>IOptions&lt;T&gt;</c> value via the constructor generated by <see cref="InjectConstructorAttribute"/>.
/// The source generator will add a constructor parameter of type <c>IOptions&lt;T&gt;</c> (where <c>T</c> is the field type) and assign the unwrapped <c>.Value</c> to this field.
/// </summary>
[Conditional(Constants.CodeGenerationCondition)]
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public class InjectedOptionsAttribute : Attribute;
