using System.Diagnostics;
using Nuons.Core.Abstractions;

namespace Nuons.CodeInjection.Abstractions;

/// <summary>
/// Marks a field to be injected via the constructor generated by <see cref="InjectConstructorAttribute"/>.
/// The source generator will add a constructor parameter whose type matches the field type and assign it to this field.
/// </summary>
[Conditional(Constants.CodeGenerationCondition)]
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public class InjectedAttribute : Attribute;
